include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unchecked_use_of_nullable_value: error
    deprecated_member_use: error

linter:
  rules:
    avoid_print: false
    # prefer_single_quotes: true
    # use_build_context_synchronously: false
    # library_private_types_in_public_api: false
    # prefer_const_constructors: false
# https://dart.dev/guides/language/analysis-options