name: smart_parents
description: "Smart Parents- College Management System"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.12.2

# flutter pub get
# flutter pub upgrade
# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.1.2
  cloud_firestore: ^6.4.1
  # connectivity_plus: ^7.1.1
  connectivity_plus: ^6.1.5
  dotted_border: ^3.1.0
  file_picker: ^12.0.0-beta.7
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_storage: ^13.4.1
  fluttertoast: ^9.1.0
  google_fonts: ^8.1.0
  google_maps_flutter: ^2.17.1
  google_nav_bar: ^5.0.7
  image_network: ^2.6.0
  image_picker: ^1.2.2
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  location: ^8.0.1
  path: ^1.9.1
  pdf: ^3.12.0
  photo_view: ^0.15.0
  printing: ^5.14.3
  quickalert: ^1.1.0
  share_plus: ^13.1.0
  shared_preferences: ^2.5.5
  syncfusion_flutter_pdfviewer: ^33.2.13+1
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/