name: smart_parents
description: Final year project 'Smart Parents'.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# flutter pub get
# flutter pub upgrade
# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

# Android:
  # flutter_local_notifications: ^13.0.0

# Web:
  # flutter_dropzone: ^3.0.5

# Android & Web:
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  flutter_datetime_picker: ^1.5.1
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.0.20
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  pdf: ^3.9.0
  printing: ^5.10.1
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  fluttertoast: ^8.2.1
  table_calendar: ^3.0.8
  dotted_border: ^2.0.0+3
  awesome_dialog: ^3.0.2
  image_network: ^2.5.1

  # image_picker_web: ^3.0.0+1
  # table_calendar: ^3.0.9
  # firebase_messaging: ^14.3.0
  # excel: ^2.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# Android:
  flutter_launcher_icons: ^0.12.0

# Web:

# Android & Web:
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  # android: "launcher_icon"
  ios: true
  image_path: "assets/images/Final.png"
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  # flutter pub get
  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/Photo/