name: smart_parents
description: Final year project 'Smart Parents'.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# flutter pub get
# flutter pub upgrade
# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

  awesome_dialog: ^3.1.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  connectivity_plus: ^4.0.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.3.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  fluttertoast: ^8.2.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.2.8
  google_nav_bar: ^5.0.6
  image_network: ^2.5.2
  image_picker: ^0.8.7+5
  internet_connection_checker: ^1.0.0+1
  location: ^4.4.0
  onesignal_flutter: ^3.5.1
  pdf: ^3.10.4
  photo_view: ^0.14.0
  printing: ^5.11.0
  share_plus: ^7.0.1
  shared_preferences: ^2.1.1
  syncfusion_flutter_pdfviewer: ^21.2.6
  table_calendar: ^3.0.9
  url_launcher: ^6.1.11

  # file_picker: ^5.3.2
  # google_fonts: ^4.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  # flutter_launcher_icons: ^0.13.1
# flutter_icons:
#   # android: true
#   android: "launcher_icon"
#   image_path: "assets/images/Final.png"
#   # flutter pub get
#   # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/