name: smart_parents
description: Final year project 'Smart Parents'.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# flutter pub get
# flutter pub upgrade
# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

# Android & Web:
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.2
  firebase_storage: ^11.1.1
  flutter_datetime_picker: ^1.5.1
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.1.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  pdf: ^3.10.1
  printing: ^5.10.3
  image_picker: ^0.8.7+3
  file_picker: ^5.2.10
  fluttertoast: ^8.2.1
  dotted_border: ^2.0.0+3
  awesome_dialog: ^3.0.2
  image_network: ^2.5.1
  url_launcher: ^6.1.10
  location: ^4.4.0
  photo_view: ^0.14.0
  share_plus: ^6.3.2
  connectivity_plus: ^3.0.4
  syncfusion_flutter_pdfviewer: ^21.1.41
  table_calendar: ^3.0.8

  # flutter_map: ^3.1.0
  # latlong2: ^0.8.1
  # firebase_messaging: ^14.4.1
  # excel: ^2.1.0
  # table_calendar: ^3.0.9

# Android:
  google_maps_flutter: ^2.2.5
  onesignal_flutter: ^3.5.1
  internet_connection_checker: ^1.0.0+1
  # pdf_viewer_plugin: ^2.0.1
  # flutter_full_pdf_viewer: ^1.0.6
  # image_gallery_saver: ^1.7.1
  # internet_popup: ^1.0.8+5
  # flutter_background_service: ^2.4.6
  # flutter_local_notifications: ^13.0.0

# Web:
  flutter_dropzone: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# Android & Web: 
  flutter_lints: ^  2.0.1
  
# Android:
  # flutter_launcher_icons: ^0.13.0
# flutter_icons:
#   # android: true
#   android: "launcher_icon"
#   remove_alpha_ios: true
#   ios: true
#   image_path: "assets/images/Final.png"
#   web:
#     generate: true
#   windows:
#     generate: true
#   macos:
#     generate: true
#   # flutter pub get
#   # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/