// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbfM3tGzej2ZlUCGihflrUpLzwGQKZzE',
    appId: '1:988559124743:web:6c66e5fabad30a6bbc3da2',
    messagingSenderId: '988559124743',
    projectId: 'smart-parents-97628',
    authDomain: 'smart-parents-97628.firebaseapp.com',
    storageBucket: 'smart-parents-97628.appspot.com',
    measurementId: 'G-FB5S6R8QZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4aAlX_j8sUDGTnEZQ8bS7nAK6T4inle8',
    appId: '1:988559124743:android:25b5408345d1e810bc3da2',
    messagingSenderId: '988559124743',
    projectId: 'smart-parents-97628',
    storageBucket: 'smart-parents-97628.appspot.com',
  );
}
